### ISSUE TITLE
Escape keywords when they match a V reserved word

### ISSUE THREAD

**Issue by Thihup** [vlang/go2v#78] opened 2022-04-27 19:54 UTC
Example:
```go
package main

type ClData struct {
	Module string
}

func main() {
	foo := ClData{}
	foo.Module = "hi"
}
```

Output:
```
/tmp/foo.v:7:5: error: unexpected keyword `module`, expecting name
    5 | }
    6 | fn main() {mut foo:=ClData{}  
    7 | foo.module='hi'  
      |     ~~~~~~
    8 | }
cli execution error: Generated output could not be formatted:
```

**Comment by JalonSolov** [comment] 2022-04-27 20:47
The problem isn't because it's capitalized, it's because `module` is a reserved word in V.  Title changed accordingly.

**Comment by Hunam6** [comment] 2022-04-27 22:23
I get the issue that's because it's checking if `.module` (instead of `module`) is a keyword, I'll fix it tomorrow or so.

**Comment by Hunam6** [comment] 2022-04-29 13:07
fixed in https://github.com/vlang/go2v/commit/ce8b7b55c0d25aae73c4b322713acce405e76820, thanks

**Closed as completed by Hunam6** 2022-04-29 13:07 UTC
